spring.application.name=home_store
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.mailersend.net
spring.mail.port=587
spring.mail.username=MS_IGm7Dl@test-y7zpl98r7m345vx6.mlsender.net
spring.mail.password=mssp.eoVfWz0.k68zxl2n1k9lj905.EB3SzRO
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

app.mail.from=no-reply@test-y7zpl98r7m345vx6.mlsender.net
app.mail.from-name=Home Store