spring.application.name=home_store
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.mailersend.net
spring.mail.port=587
spring.mail.username=MS_AgtcCo@test-r6ke4n1y7vygon12.mlsender.net
spring.mail.password=mssp.cXxmEIA.jpzkmgqr80v4059v.bZsAgK8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true