spring.application.name=home_store
spring.jpa.hibernate.ddl-auto=update

# MAIL - konfiguracja testowa
# Najlepiej u?y? Mailtrap albo Gmail App Password.
spring.mail.host=Wpisz tutaj
spring.mail.port=Wpisz tutaj
spring.mail.username=Wpisz tutaj
spring.mail.password=Wpisz tutaj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true