package com.example.home_store.model.enum_model;

public enum ProductType {

    // SALON
    LIVING_ROOM_SOFA,
    LIVING_ROOM_COFFEE_TABLE,
    LIVING_ROOM_BOOKCASE,
    LIVING_ROOM_ARMCHAIR,

    // SYPIALNIA
    BEDROOM_BED,
    BEDROOM_WARDROBE,
    BEDROOM_CHEST_OF_DRAWERS,
    BEDROOM_NIGHT_STAND,

    // KUCHNIA
    KITCHEN_TABLE,
    KITCHEN_CHAIR,
    KITCHEN_SINK,
    KITCHEN_CABINET,
    KITCHEN_BAR_STOOL,

    // ŁAZIENKA
    BATHROOM_SINK_CABINET,
    BATHROOM_BATH,
    BATHROOM_STORAGE_CABINET,
    BATHROOM_SHELF,
    BATHROOM_LAUNDRY_BASKET,

    // BIURO
    OFFICE_DESK,
    OFFICE_CHAIR,
    OFFICE_BOOKCASE,
    OFFICE_FILE_CABINET,

    // PRZEDPOKÓJ
    HALLWAY_SHOE_CABINET,
    HALLWAY_COAT_RACK,
    HALLWAY_BENCH,
    HALLWAY_MIRROR,

    // RTV
    TELEVISION,
    SOUND_SYSTEM,
    HOME_THEATER,
    MEDIA_PLAYER,
    GAME_CONSOLE,

    // AGD
    REFRIGERATOR,
    DISHWASHER,
    WASHING_MACHINE,
    DRYER,
    OVEN,
    MICROWAVE,
    COFFEE_MACHINE,
    KETTLE,
    TOASTER,
    BLENDER,
    VACUUM_CLEANER,
    IRON,
    AIR_PURIFIER;

}
